global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    cluster: user-notification-platform
    environment: local

alerting:
  alertmanagers:
    - static_configs:
        - targets: ["alertmanager:9093"]

rule_files:
  - /etc/prometheus/alerts.yml

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'user-service'
    metrics_path: /actuator/prometheus
    static_configs:
      - targets: ['user-service:8081']
        labels:
          service: user-service

  - job_name: 'notification-service'
    metrics_path: /actuator/prometheus
    static_configs:
      - targets: ['notification-service:8081']
        labels:
          service: notification-service

  - job_name: 'api-gateway'
    metrics_path: /actuator/prometheus
    static_configs:
      - targets: ['api-gateway:8080']
        labels:
          service: api-gateway

  - job_name: 'web-bff'
    metrics_path: /actuator/prometheus
    static_configs:
      - targets: ['web-bff:8090']
        labels:
          service: web-bff

  - job_name: 'config-server'
    metrics_path: /actuator/prometheus
    static_configs:
      - targets: ['config-server:8888']
        labels:
          service: config-server
