platform:
  environment: ${PLATFORM_ENVIRONMENT:docker}

management:
  endpoints:
    web:
      base-path: /actuator
  endpoint:
    health:
      probes:
        enabled: true

logging:
  level:
    root: INFO
    AUDIT: INFO
