platform:
  environment: kubernetes

server:
  shutdown: graceful

spring:
  lifecycle:
    timeout-per-shutdown-phase: 30s
  cloud:
    discovery:
      client:
        simple:
          instances:
            user-service:
              - uri: https://user-service:8443
            notification-service:
              - uri: https://notification-service:8443
            api-gateway:
              - uri: ${API_GATEWAY_URI:https://api-gateway:8080}
