spring:
  config:
    import: optional:classpath:platform/eureka-defaults.yml

eureka:
  instance:
    instance-id: ${spring.application.name}:${random.value}
    hostname: ${EUREKA_INSTANCE_HOSTNAME:${HOSTNAME:web-bff}}
