{{- if .Values.externalSecrets.enabled }}
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ include "platform.fullname" . }}-secrets
spec:
  refreshInterval: {{ .Values.externalSecrets.refreshInterval }}
  secretStoreRef:
    name: {{ .Values.externalSecrets.secretStoreName }}
    kind: {{ .Values.externalSecrets.secretStoreKind }}
  target:
    name: {{ include "platform.fullname" . }}-secrets
    creationPolicy: Owner
  data:
    - secretKey: APP_JWT_SECRET
      remoteRef:
        key: {{ .Values.externalSecrets.remoteKey }}
        property: appJwtSecret
    - secretKey: APP_SERVICE_JWT_SECRET
      remoteRef:
        key: {{ .Values.externalSecrets.remoteKey }}
        property: appServiceJwtSecret
    - secretKey: APP_SEED_ADMIN_PASSWORD
      remoteRef:
        key: {{ .Values.externalSecrets.remoteKey }}
        property: seedAdminPassword
    - secretKey: APP_SEED_USER_PASSWORD
      remoteRef:
        key: {{ .Values.externalSecrets.remoteKey }}
        property: seedUserPassword
    - secretKey: DB_PASSWORD
      remoteRef:
        key: {{ .Values.externalSecrets.remoteKey }}
        property: dbPassword
    - secretKey: APP_API_KEYS
      remoteRef:
        key: {{ .Values.externalSecrets.remoteKey }}
        property: apiKeys
{{- end }}
