{{- if not .Values.externalSecrets.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "platform.fullname" . }}-secrets
type: Opaque
stringData:
  APP_JWT_SECRET: {{ .Values.secrets.appJwtSecret | quote }}
  APP_SERVICE_JWT_SECRET: {{ .Values.secrets.appServiceJwtSecret | quote }}
  APP_SEED_ADMIN_PASSWORD: {{ .Values.secrets.seedAdminPassword | quote }}
  APP_SEED_USER_PASSWORD: {{ .Values.secrets.seedUserPassword | quote }}
  DB_PASSWORD: {{ .Values.infra.postgres.password | default .Values.externalDatabase.postgres.password | quote }}
{{- end }}
