name: user-service local-1
values:
  - key: baseUrl
    value: 'https://localhost:8443'
  - key: adminUser
    value: admin
  - key: adminPass
    value: admin123
  - key: regularUser
    value: user
  - key: regularPass
    value: user123
  - key: userId
    value: '1'
  - key: secondUserId
    value: '2'
  - key: noteId
    value: '1'
  - key: roleId
    value: '1'
  - key: roleIdAdmin
    value: '1'
  - key: roleIdUser
    value: '2'
  - key: customRoleId
    value: '3'
  - key: accessToken
    value: ''
  - key: refreshToken
    value: ''
